### ISSUE TITLE
Regression A/V problem: multiple media files in one canvas

### ISSUE THREAD

**Issue by mcwhitaker** [UniversalViewer/universalviewer#779]
**UV version:**

```
https://uv-v3.netlify.app/
```

**I'm submitting a:**

- [X ] bug report
- [ ] feature request => please use the [user stories repo](https://github.com/UniversalViewer/user-stories)
- [ ] support request => Please do not submit support requests here, use [stackoverflow](http://stackoverflow.com/questions/tagged/iiif)

**Current behavior:**
We added a link to the UV in the IIIF Cookbook for [recipe # 64, Opera in One Canvas](https://iiif.io/api/cookbook/recipe/0064-opera-one-canvas/). This recipe demonstrates the ability to use one single canvas for multiple A/V files, each using a fragment of the time. Part of approving the process was to demo it, which was done using UV (see [recording on minute 38:58](https://stanford.zoom.us/rec/play/6Jx-cOn8qG43TNeXtgSDV_8tW467Ka2s0CgcrKFcnUy9B3IDZAD1Z-QSa-fvO0Ju73GBmX77KRk7rD2v)).

The link demonstrated in the video no longer works. UV does not play the second file.

**Expected behavior:**
We expected the UV link in the recipe mentioned above to still work.

**Steps to reproduce:**
Go to the recipe, and click on the link _View in Universal Viewer_ and try to navigate to _Atto Secondo_.

**Related code:**

```
// insert any relevant code here
```

**Other information:**

**Comment by glenrobson** [comment]
Has this been fixed? I was just testing the cookbook UV link and the table of contents seems to be working :-).

**Comment by mcwhitaker** [comment]
Yes, but now the video doesn't show on the viewer? The playhead moves and is correctly showing two files. @glenrobson is the video playing correctly for you?

**Comment by glenrobson** [comment]
Ah no... you're right I got too carried away with the playhead moving and didn't click play...

**Comment by edsilv** [comment]
link to manifest: https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fiiif.io%2Fapi%2Fcookbook%2Frecipe%2F0064-opera-one-canvas%2Fmanifest.json

**Comment by markpbaggett** [comment]
Hi @edsilv, the commit above suggests that this issue was fixed, but it still seems to be failing in v3 and v4 of UV.  Is this a known issue, or something that has popped back up?

**Comment by edsilv** [comment]
@markpbaggett This appears to be working in 4.0.1? https://www.universalviewer.dev/#?c=&m=&cv=&xywh=-2494%2C-197%2C7556%2C3936&rid=%5Bobject%20Object%5D&t=11.57800006866455

However, @stephenwf there's a scaling issue with the video where it's overlapping the share and download buttons.

**Comment by stephenwf** [comment]
Looks like that might be unrelated to video. Fixed inline by removing the `style="height: 570px"` which doesn't take into account the 20px of padding in the parent on 2 inner elements (`.views` and `.resourcesView > ul`)

<img width="478" alt="Screenshot 2022-06-28 at 15 28 54" src="https://user-images.githubusercontent.com/8266711/176204704-235a81f5-81a5-4732-a391-c43df2fda249.png">

**Comment by markpbaggett** [comment]
@edsilv and @stephenwf, hmmmm. I'm still getting the same error in v4.0.1 with the manifest in the recipe:

https://iiif.io/api/cookbook/recipe/0064-opera-one-canvas/manifest.json

Everything is good until we get to the second annotation on the Canvas at 3971.24. The duration keeps going in the viewer, but the second annotation doesn't appear.

I also threw together a quick gist of my own that has the same problem:

https://gist.githubusercontent.com/markpbaggett/f742e2bc857d2e76de8fdcbeb002c3fc/raw/8ac894955c43ce29c26abe2e3241d997f9faab94/wwiioh_2002.json

All is good until we get to the second annotation.

**Comment by jwd** [comment]
I'm also still seeing the same problem as @markpbaggett with v4.0.1: 
https://www.universalviewer.dev/#?xywh=-714%2C-197%2C3996%2C3936&iiifManifestId=https%3A%2F%2Fiiif.io%2Fapi%2Fcookbook%2Frecipe%2F0064-opera-one-canvas%2Fmanifest.json

**Comment by LlGC-szw** [comment]
All issues will be triaged for further investigation or closure by the 28 September 2023. If your issue is still relevant and would like for it be investigated further please comment by 14 September 2023.

**Comment by edsilv** [comment]
related? https://github.com/pulibrary/figgy/pull/2524/files
